# --- App Configuration ---
app.frontend-url=localhost:8080
app.jwt.secret=2f7c7fdb2b9c4a91802d4e09b56c8243b8a7e621a2cf0534fda5c5a63e913f5c
app.jwt.expiration=1800000

# --- H2 in-memory ---
spring.datasource.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- H2 Console ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Logging ---
logging.level.com.cardealer=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# --- Mail ---
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=38a15e669ffa65
spring.mail.password=01f2a6ae63e0b0
spring.mail.protocol=smtp

# Enable authentication and TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true